#ifndef RUST_FFI_H
#define RUST_FFI_H

#include "postgres.h"

void		vector_rust_init(void);
const char *vector_rust_bridge_version_cstr(void);
const char *vector_rust_ivfflat_handler_probe_cstr(void);
const char *vector_rust_hnsw_handler_probe_cstr(void);
bool		vector_rust_hnsw_should_reject_closer_neighbor_kernel(double distance, double candidate_distance);
bool		vector_rust_hnsw_can_add_duplicate_heap_tid_kernel(int32 heaptids_length, int32 max_heaptids);
bool		vector_rust_hnsw_should_select_neighbors_early_return_kernel(int32 candidate_count, int32 max_neighbors);
bool		vector_rust_hnsw_should_repair_underfilled_layer0_kernel(bool last_item_valid);
bool		vector_rust_hnsw_should_flush_graph_kernel(int64 memory_used, int64 memory_total);
bool		vector_rust_hnsw_should_use_ondisk_phase_kernel(bool graph_flushed);
bool		vector_rust_hnsw_should_add_search_candidate_kernel(double candidate_distance, double frontier_distance, bool always_add);
bool		vector_rust_hnsw_should_stop_search_layer_kernel(double candidate_distance, double frontier_distance);
bool		vector_rust_hnsw_should_append_neighbor_without_prune_kernel(int32 neighbors_length, int32 max_neighbors);
bool		vector_rust_hnsw_should_skip_lower_level_candidate_kernel(int32 candidate_level, int32 search_level);
bool		vector_rust_hnsw_should_keep_pruned_connection_kernel(int32 wdoff, int32 wdlen, int32 result_length, int32 max_neighbors);
bool		vector_rust_hnsw_should_set_pruned_from_array_kernel(int32 wdoff, int32 wdlen);
bool		vector_rust_hnsw_should_track_discarded_candidates_kernel(bool has_discarded_heap);
bool		vector_rust_hnsw_should_track_update_index_kernel(bool has_update_index_pointer);
bool		vector_rust_hnsw_should_process_pruned_candidate_kernel(bool has_pruned_candidate);
bool		vector_rust_hnsw_should_trim_candidate_list_kernel(int32 candidate_count, int32 ef);
bool		vector_rust_hnsw_should_always_add_candidate_kernel(int32 candidate_count, int32 ef);
bool		vector_rust_hnsw_should_update_entry_point_kernel(bool entry_point_is_null, int32 element_level, int32 entry_level);
bool		vector_rust_hnsw_should_flush_pages_in_build_kernel(bool graph_flushed);
bool		vector_rust_hnsw_should_disable_without_order_kernel(int32 orderby_count);
double		vector_rust_hnsw_clamp_ratio_kernel(double ratio);
bool		vector_rust_hnsw_should_adjust_startup_cost_kernel(double startup_pages, double rel_pages, double ratio);
bool		vector_rust_hnsw_should_return_empty_without_entrypoint_kernel(bool entry_point_is_null);
bool		vector_rust_hnsw_should_resume_from_discarded_kernel(bool discarded_is_empty);
bool		vector_rust_hnsw_should_return_remaining_discarded_kernel(bool discarded_is_empty);
bool		vector_rust_hnsw_should_skip_strict_out_of_order_kernel(int32 iterative_scan_mode, double distance, double previous_distance);
bool		vector_rust_hnsw_should_stop_without_discarded_kernel(bool discarded_is_null);
bool		vector_rust_hnsw_should_stop_when_iterative_scan_off_kernel(int32 iterative_scan_mode);
bool		vector_rust_hnsw_should_limit_scan_by_resources_kernel(int64 tuple_count, int64 max_scan_tuples, int64 memory_used, int64 max_memory);
void		vector_rust_ivfflat_adjust_cost_kernel(double index_total_cost, double num_index_pages, double random_page_cost, double seq_page_cost, double ratio, double rel_pages, double sequential_ratio, double *adjusted_total_cost, double *adjusted_startup_cost);
double		vector_rust_ivfflat_probe_ratio_kernel(int32 probes, int32 lists);
bool		vector_rust_ivfflat_should_disable_without_order_kernel(int32 orderby_count);
bool		vector_rust_ivfflat_choose_insert_candidate_kernel(double distance, double min_distance, bool insert_page_is_valid);
bool		vector_rust_ivfflat_choose_scan_list_candidate_kernel(double distance, int32 list_count, int32 max_probes, double max_distance);
bool		vector_rust_ivfflat_should_scan_next_list_kernel(int32 list_index, int32 max_probes, int32 batch_probes, int32 probes);
bool		vector_rust_ivfflat_choose_build_center_candidate_kernel(double distance, double min_distance);
bool		vector_rust_ivfflat_should_append_page_kernel(int32 free_space, int32 item_size);
bool		vector_rust_ivfflat_should_follow_insert_page_link_kernel(int32 insert_page);
bool		vector_rust_ivfflat_should_set_insert_page_kernel(int32 ndeletable, bool insert_page_is_valid);
bool		vector_rust_ivfflat_should_update_insert_page_kernel(int32 insert_page, int32 original_insert_page);
bool		vector_rust_ivfflat_should_allow_insert_page_after_original_kernel(int32 insert_page, int32 original_insert_page);
bool		vector_rust_ivfflat_should_reuse_scan_slot_kernel(int32 list_count, int32 max_probes);
void		vector_rust_ivfflat_scan_probe_limits_kernel(int32 probes, int32 max_probes, int32 lists, int32 *adjusted_probes, int32 *adjusted_max_probes);
void		vector_rust_ivfflat_compute_scan_limits_kernel(int32 probes, int32 max_probes, int32 lists, int32 iterative_scan_mode, int32 *adjusted_probes, int32 *adjusted_max_probes);
bool		vector_rust_ivfflat_should_load_more_scan_items_kernel(int32 list_index, int32 max_probes);
uint64		vector_rust_bit_hamming_distance(uint32 bytes, unsigned char *ax, unsigned char *bx, uint64 distance);
double		vector_rust_bit_jaccard_distance(uint32 bytes, unsigned char *ax, unsigned char *bx, uint64 ab, uint64 aa, uint64 bb);
float		vector_rust_half_l2_squared_distance(int dim, const void *ax, const void *bx);
float		vector_rust_half_inner_product(int dim, const void *ax, const void *bx);
double		vector_rust_half_cosine_similarity(int dim, const void *ax, const void *bx);
float		vector_rust_half_l1_distance(int dim, const void *ax, const void *bx);
float		vector_rust_vector_l2_squared_distance(int dim, const float *ax, const float *bx);
float		vector_rust_vector_inner_product(int dim, const float *ax, const float *bx);
double		vector_rust_vector_cosine_similarity(int dim, const float *ax, const float *bx);
float		vector_rust_vector_l1_distance(int dim, const float *ax, const float *bx);
void		vector_rust_vector_add(int dim, const float *ax, const float *bx, float *rx);
void		vector_rust_vector_sub(int dim, const float *ax, const float *bx, float *rx);
void		vector_rust_vector_mul(int dim, const float *ax, const float *bx, float *rx);
void		vector_rust_vector_concat(int adim, const float *ax, int bdim, const float *bx, float *rx);
double		vector_rust_vector_norm(int dim, const float *ax);
void		vector_rust_vector_l2_normalize(int dim, const float *ax, float *rx);
void		vector_rust_vector_binary_quantize(int dim, const float *ax, unsigned char *rx);
void		vector_rust_vector_subvector(int dim, const float *ax, int start_index, float *rx);
int32		vector_rust_vector_cmp(int adim, const float *ax, int bdim, const float *bx);
void		vector_rust_vector_copy_f64(int dim, const double *src, double *dst);
void		vector_rust_vector_accum_init(int dim, const float *x, double *dst);
void		vector_rust_vector_accum_add(int dim, const double *state, const float *x, double *dst);
void		vector_rust_vector_combine_add(int dim, const double *a, const double *b, double *dst);
void		vector_rust_vector_avg(int dim, const double *state, double n, float *dst);
void		vector_rust_halfvec_to_vector(int dim, const void *ax, float *rx);
void		vector_rust_vector_to_halfvec_kernel(int dim, const float *ax, void *rx);
void		vector_rust_sparse_to_halfvec_kernel(int nnz, const int32 *indices, const float *values, void *rx);
void		vector_rust_sparse_to_dense(int nnz, const int32 *indices, const float *values, float *rx);
int32		vector_rust_vector_to_sparse_count_kernel(int dim, const float *ax);
int32		vector_rust_vector_to_sparse_fill_kernel(int dim, const float *ax, int32 *indices, float *values);
int32		vector_rust_halfvec_to_sparse_count_kernel(int dim, const void *ax);
int32		vector_rust_halfvec_to_sparse_fill_kernel(int dim, const void *ax, int32 *indices, float *values);
void		vector_rust_ivfflat_center_counts_kernel(int sample_count, const int32 *closest_centers, int center_count, int32 *counts);
void		vector_rust_ivfflat_zero_agg_kernel(int center_count, int dimensions, float *agg);
void		vector_rust_ivfflat_finalize_center_kernel(int dimensions, float *agg, int center_count);
bool		vector_rust_ivfflat_all_finite_kernel(int dimensions, const float *values);
void		vector_rust_ivfflat_vector_sum_center_kernel(int dimensions, const float *center, float *agg);
void		vector_rust_ivfflat_bit_sum_center_kernel(int dimensions, const unsigned char *bits, float *agg);
void		vector_rust_ivfflat_vector_update_center_kernel(int dimensions, const float *values, float *output);
void		vector_rust_ivfflat_bit_update_center_kernel(int dimensions, const float *values, unsigned char *output);
void		vector_rust_ivfflat_halfvec_update_center_kernel(int dimensions, const float *values, void *output);
void		vector_rust_ivfflat_halfvec_sum_center_kernel(int dimensions, const void *halfvec, float *agg);
void		vector_rust_ivfflat_adjust_lower_bounds_kernel(int sample_count, int center_count, float *lower_bounds, const float *center_distances);
void		vector_rust_ivfflat_adjust_upper_bounds_kernel(int sample_count, float *upper_bounds, const int32 *closest_centers, const float *center_distances);
void		vector_rust_ivfflat_init_bounds_kernel(int sample_count, int center_count, const float *lower_bounds, float *upper_bounds, int32 *closest_centers);
void		vector_rust_ivfflat_compute_s_kernel(int center_count, const float *halfcdist, float *s);
void		vector_rust_halfvec_add_kernel(int dim, const void *ax, const void *bx, float *rx);
void		vector_rust_halfvec_sub_kernel(int dim, const void *ax, const void *bx, float *rx);
void		vector_rust_halfvec_mul_kernel(int dim, const void *ax, const void *bx, float *rx);
void		vector_rust_halfvec_concat_kernel(int adim, const void *ax, int bdim, const void *bx, float *rx);
void		vector_rust_halfvec_binary_quantize_kernel(int dim, const void *ax, unsigned char *rx);
void		vector_rust_halfvec_subvector_kernel(int dim, const void *ax, int start_index, void *rx);
double		vector_rust_halfvec_l2_norm_kernel(int dim, const void *ax);
void		vector_rust_halfvec_l2_normalize_kernel(int dim, const void *ax, float *rx);
int32		vector_rust_halfvec_cmp_kernel(int adim, const void *ax, int bdim, const void *bx);
void		vector_rust_halfvec_accum_init_kernel(int dim, const void *ax, double *dst);
void		vector_rust_halfvec_accum_add_kernel(int dim, const double *state, const void *ax, double *dst);
float		vector_rust_sparsevec_l1_distance_kernel(int annz, const int32 *aindices, const float *ax, int bnnz, const int32 *bindices, const float *bx);
float		vector_rust_sparsevec_l2_squared_distance_kernel(int annz, const int32 *aindices, const float *ax, int bnnz, const int32 *bindices, const float *bx);
float		vector_rust_sparsevec_inner_product_kernel(int annz, const int32 *aindices, const float *ax, int bnnz, const int32 *bindices, const float *bx);
double		vector_rust_sparsevec_cosine_distance_kernel(int annz, const int32 *aindices, const float *ax, int bnnz, const int32 *bindices, const float *bx);
double		vector_rust_sparsevec_l2_norm_kernel(int nnz, const float *ax);
void		vector_rust_sparsevec_l2_normalize_values_kernel(int nnz, const float *ax, double norm, float *rx);
int32		vector_rust_sparsevec_cmp_kernel(int adim, int annz, const int32 *aindices, const float *ax, int bdim, int bnnz, const int32 *bindices, const float *bx);

#endif
